spring:
  application:
  name: cineLog
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cineLog
      auto-index-creation: true


logging:
  level:
    org:
      springframework=DEBUG:
