spring:
  application:
  name: cineLog
  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster0.r4qyc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

      database: cineLog
      auto-index-creation: true


logging:
  level:
    org:
      springframework=DEBUG:
